config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'settings' => 'devise/registrations#edit', as: 'edit_settings'
  end

  get 'verify_phone' => 'phone#verify', as: 'verify_phone'
  post 'verify_phone' => 'phone#check_pin', as: 'check_pin'

  get 'about' => 'about#index', as: 'about'

  get 'billing' => 'billing#index', as: 'billing'

  resources :trails do
    member do
      get 'admin'
      post 'create_photo'
    end
  end
  resources :instagram_photos, only: :destroy
  resources :alerts
  resource :subscriptions, as: :subscription
end

app/controllers/phone_controller.rb
class PhoneController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_already_verified
  before_action :redirect_no_phone_number

  def verify
    reset_pin!
    text_pin!
  end

  def check_pin
    if params[:pin] == current_user.phone_pin
      flash[:success] = 'You successfully verified your phone number!'
      current_user.update_attribute('phone_verified', true)
      redirect_to(edit_settings_path)
    else
      flash[:error] = 'The PIN you entered did not match the PIN we sent. Try again.'
      render :verify
    end
  end

private
  def reset_pin!
    current_user.update_attribute('phone_pin', rand(0000..9999).to_s.rjust(4, '0'))
  end

  def text_pin!
    $twilio_client.messages.create(
      from: $twilio_phone_number,
      to: current_user.phone_number,
      body: "Hi there! This is MTB Trail Status verifying your phone number. Your PIN is #{current_user.phone_pin}."
    )
  end

  def redirect_already_verified
    if current_user.phone_verified
      redirect_to(edit_settings_path)
    end
  end

  def redirect_no_phone_number
    if current_user.phone_number.blank?
      flash[:notice] = 'Set your phone number before verifying it.'
      redirect_to edit_settings_path
    end
  end
end

app/views/phone/verify.html.haml
.full-panel
  .container
    .jumbotron.form
      %h2
        Verify #{current_user.phone_number}
      %p
        We just sent a text message to the phone number above. Enter the PIN you see in the text message to verify.
      = form_tag(check_pin_path, method: 'post', class: 'form-inline') do
        .form-group
          = label_tag(:pin, 'Pin: ')
          = text_field_tag(:pin, '', autofocus: true, class: 'form-control')
        = submit_tag('Verify', class: 'btn btn-success')