config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'settings' => 'devise/registrations#edit', as: 'edit_settings'
  end

  get 'verify_phone' => 'phone#verify', as: 'verify_phone'
  post 'verify_phone' => 'phone#check_pin', as: 'check_pin'

  get 'about' => 'about#index', as: 'about'

  get 'billing' => 'billing#index', as: 'billing'

  resources :trails do
    member do
      get 'admin'
      post 'create_photo'
    end
  end
  resources :instagram_photos, only: :destroy
  resources :alerts
  resource :subscriptions, as: :subscription
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail

  validates(:user, uniqueness: { scope: :trail, message: "alert already exists for this trail." })
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  include TrailLoader

  authorize_resource

  before_action :authenticate_user!
  before_action :load_trails, only: [:index]

  def index
    @nav = 'alerts'
    @current_email_alert_trails = current_user.alerts.where(email: true).collect{ |a| a.trail }
    @current_sms_alert_trails   = current_user.alerts.where(sms: true).collect{ |a| a.trail }
  end

  def create
    trail_sms_ids   = params[:trail_sms]   ? params[:trail_sms][:ids].map!(&:to_i)   : []
    trail_email_ids = params[:trail_email] ? params[:trail_email][:ids].map!(&:to_i) : []

    trail_sms_ids.each do |trail_id|
      trail = Trail.find trail_id
      alert = Alert.find_or_initialize_by(user: current_user, trail: trail)
      alert.sms = true
      alert.save
    end

    trail_email_ids.each do |trail_id|
      trail = Trail.find trail_id
      alert = Alert.find_or_initialize_by(user: current_user, trail: trail)
      alert.email = true
      alert.save
    end

    current_user.alerts.each do |alert|
      alert.sms   = false unless trail_sms_ids.include?(alert.trail.id)
      alert.email = false unless trail_email_ids.include?(alert.trail.id)

      if alert.sms || alert.email
        alert.save
      else
        alert.destroy
      end
    end

    flash[:success] = 'Your trail alerts were updated!'
    redirect_to alerts_path
  end
end

app/views/alerts/index.html.haml
.full-panel
  .container
    .jumbotron.form
      %h2 Setup Your Trail Alerts

      - sms_disabled = !current_user.can_receive_texts?
      - if sms_disabled
        - if !current_user.phone_verified?
          .alert.alert-info #{link_to 'Verify your phone number', verify_phone_path, class: 'add'} to enable SMS alerts.
        - else
          .alert.alert-info #{link_to 'Add a subscription', new_subscription_path, class: 'add'} to enable SMS alerts.

      = form_tag(alerts_path, method: 'post', class: 'form-horizontal') do
        %table.table
          %thead
            %tr
              %th
              %th SMS
              %th Email
          %tbody
            - @trails.each do |trail|
              %tr
                %td= trail.name
                %td.input= check_box_tag('trail_sms[ids][]',   trail.id, @current_sms_alert_trails.include?(trail), disabled: sms_disabled)
                %td.input= check_box_tag('trail_email[ids][]', trail.id, @current_email_alert_trails.include?(trail))
          %tfoot
            %tr
              %td{colspan: '3'}= submit_tag('Save', class: 'btn btn-success save')