config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'settings' => 'devise/registrations#edit', as: 'edit_settings'
  end

  get 'verify_phone' => 'phone#verify', as: 'verify_phone'
  post 'verify_phone' => 'phone#check_pin', as: 'check_pin'

  get 'about' => 'about#index', as: 'about'

  get 'billing' => 'billing#index', as: 'billing'

  resources :trails do
    member do
      get 'admin'
      post 'create_photo'
    end
  end
  resources :instagram_photos, only: :destroy
  resources :alerts
  resource :subscriptions, as: :subscription
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan

  validates :term_start_date, :term_end_date, :stripe_customer_id, :stripe_subscription_id, :card_info, presence: true

  serialize :card_info, JSON

  def active?
    today = Date.today
    term_start_date <= today && term_end_date >= today
  end

  def cancel!
    customer = Stripe::Customer.retrieve(stripe_customer_id)
    customer.subscriptions.retrieve(stripe_subscription_id).delete
    self.update_attribute(:canceled, true)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_plans,                only: [:new, :edit, :create]
  before_action :load_stripe,               only: [:new, :edit, :create]
  before_action :redirect_no_subscription,  only: [:edit]
  before_action :redirect_has_subscription, only: [:new]
  before_action :load_current_subscription, only: [:edit, :destroy, :new, :update, :create]

  def new

  end

  def edit

  end

  def create
    plan_id      = params[:plan]
    stripe_token = params[:stripe_token]

    begin
      customer = Stripe::Customer.create(
        source: stripe_token,
        plan:   plan_id,
        email:  current_user.email
      )
    rescue Stripe::CardError => e
      body  = e.json_body
      error = body[:error][:message]

      puts 'There was a problem with a card: ', body[:error]

      flash[:error] = "There was a problem with your card: #{error}"
      render new_subscription_path and return
    end
    stripe_subscription = customer.subscriptions.data[0]

    card_info = { last_4: params[:last_4], month: params[:exp_month],
                  year: params[:exp_year], brand: params[:brand] }


    plan       = Plan.find_by_stripe_id(plan_id)
    start_date = Time.at(stripe_subscription.current_period_start).to_date
    end_date   = Time.at(stripe_subscription.current_period_end).to_date

    @subscription = current_user.build_subscription(
      plan:                   plan,
      stripe_customer_id:     customer.id,
      stripe_subscription_id: stripe_subscription.id,
      card_info:              card_info,
      term_start_date:        start_date,
      term_end_date:          end_date)

    if @subscription.save
      flash[:success] = 'Your subscription is active!'
      redirect_to root_path
    else
      puts 'Error saving subscription: ', @subscription.errors.full_messages
      flash[:error] = 'There was a problem creating your subscription.'
      render new_subscription_path
    end
  end

  def update
    plan_id = params[:plan]
    plan    = Plan.find_by_stripe_id(plan_id)

    unless @current_subscription.canceled?
      @current_subscription.cancel!
    end

    customer            = Stripe::Customer.retrieve(@current_subscription.stripe_customer_id)
    stripe_subscription = customer.subscriptions.create(plan: plan.stripe_id)
    start_date          = Time.at(stripe_subscription.current_period_start).to_date
    end_date            = Time.at(stripe_subscription.current_period_end).to_date

    update_attrs = { term_start_date: start_date, term_end_date: end_date,
                     stripe_subscription_id: stripe_subscription.id, plan: plan,
                     canceled: false}

    if @current_subscription.update(update_attrs)
      flash[:success] = 'Your subscription is active!'
      redirect_to root_path
    else
      flash[:error] = 'There was a problem changing your subscription.'
      render :edit
    end
  end

  def destroy
    @current_subscription.cancel!
    flash[:notice] = 'Your subscription has been canceled.'
    redirect_to root_path
  end

private
  def load_plans
    @plans = Plan.all.order('name DESC')
  end

  def load_stripe
    @stripejs = true
  end

  def load_current_subscription
    @current_subscription = current_user.subscription
  end

  def redirect_no_subscription
    redirect_to new_subscription_path unless current_user.subscription
  end

  def redirect_has_subscription
    redirect_to edit_subscription_path if current_user.subscription
  end
end

app/views/subscriptions/_new_or_edit.html.haml
:javascript
  window.mtb.plans = {};
.container-fluid
  .plans.row
    .plan.col-xs-10.col-xs-offset-1.col-md-offset-0.col-md-4
      .plan-inner.free
        %h3 Free
        %p Limited to email alerts
        %p &nbsp;
        %p &nbsp;
        .price
          %h2 $0
          %p.per-term &nbsp;
        .action
          - if !@current_subscription || @current_subscription.canceled?
            = link_to 'Current Plan', 'javascript:void(0);', class: 'btn btn-default disabled'
          - else
            = link_to 'Choose Free', subscription_path, method: :delete, 'data-confirm' => 'Are you sure you want to cancel your subscription?', class: 'btn btn-default'
    - @plans.each do |plan|
      .plan.col-xs-10.col-xs-offset-1.col-md-offset-0.col-md-4
        .plan-inner{class: plan.stripe_id}
          %h3= plan.name
          %p SMS and Email alerts
          - if plan.name == 'Monthly'
            %p Auto-renews every month
            %p Cancel any time
          - else
            %p Annual subscription
            %p Save $7!
          .price
            %h2
              $#{plan.price_in_cents / 100}
              :javascript
                window.mtb.plans["#{plan.stripe_id}"] = {name: "#{plan.name}", price_in_cents: parseInt("#{plan.price_in_cents}")};
            %p.per-term per #{plan.name == 'Monthly' ? 'month' : 'year'}
          .action
            - if @current_subscription && @current_subscription.plan == plan && !@current_subscription.canceled?
              = link_to 'Current Plan', 'javascript:void(0);', class: 'btn btn-default disabled'
            - else
              = link_to "Choose #{plan.name}", "##{plan.name}", class: 'btn btn-primary select-plan', 'data-plan' => plan.stripe_id

.container-fluid
  .row
    .summary.col-xs-10.col-xs-offset-1.col-md-offset-0.col-md-12
      %p.summary-text
      - if @current_subscription && @current_subscription.card_info
        = form_tag(subscription_path, method: :put, class: 'form-horizontal subscription-form update-subscription-form') do
          .alert.alert-danger.card-errors
          = hidden_field_tag('plan')
          %p
            We'll charge the card you have on file, a
            %strong #{@current_subscription.card_info['brand']}
            ending in
            %span
              %strong> #{@current_subscription.card_info['last_4']}
              \.
          .form-group
            %p.text-centered
              - submit_text = @current_subscription.canceled? ? 'Purchase' : 'Change Subscription'
              = submit_tag(submit_text, class: 'btn btn-success submit')
      - else
        = form_tag(subscription_path, class: 'form-horizontal subscription-form new-subscription-form') do
          .alert.alert-danger.card-errors
          = hidden_field_tag('plan')
          .form-group
            = label_tag('', 'Card #', class: 'col-sm-3 control-label')
            .col-sm-9
              %input{type: 'text', class: 'form-control card-number', 'data-stripe' => 'number', required: 'yup'}
          .form-group
            = label_tag('', 'Expiration', class: 'col-sm-3 control-label')
            .col-sm-9
              = select_month(Date.today,
                             {field_name: 'exp_month'},
                             {class: 'form-control card-month', 'data-stripe' => 'exp-month'})
              = select_year(Date.today,
                            {field_name: 'exp_year', start_year: Date.today.year, end_year: (Date.today + 10.years).year},
                            {class: 'form-control card-year', 'data-stripe' => 'exp-year'})
          .form-group
            = label_tag('', 'CVC', class: 'col-sm-3 control-label', required: 'yup')
            .col-sm-9
              %input{type: 'text', class: 'form-control card-cvc', 'data-stripe' => 'cvc', size: '4'}
          .form-group
            .col-sm-offset-3.col-sm-9
              = submit_tag('Purchase', class: 'btn btn-success submit')

app/views/subscriptions/edit.html.haml
.container
  %h2 Change Your Subscription
  .alert.alert-info
    - if @current_subscription && @current_subscription.active? && @current_subscription.canceled?
      You have a canceled #{@current_subscription.plan.name} subscription that is still active until #{@current_subscription.term_end_date}.
    - elsif @current_subscription && @current_subscription.canceled?
      You have a canceled #{@current_subscription.plan.name} subscription.
    - else
      You currently have a recurring #{@current_subscription.plan.name} subscription.
    View #{link_to 'detailed billing', billing_path} info.
  = render 'new_or_edit'
  - unless @current_subscription.canceled?
    %hr
    %h2 Cancel Your Subscription
    %p We're sad to see you go, but we understand. Click below to cancel your current subscription. You will not be billed again, and you'll continue to receive text alerts until your current subscription period ends on #{@current_subscription.term_end_date}.
    %p.text-centered
      = link_to 'Cancel Subscription', subscription_path, method: :delete, 'data-confirm' => 'Are you sure you want to cancel your subscription?', class: 'btn btn-danger cancel'

app/views/subscriptions/new.html.haml
.container
  %h2 Change Your Subscription
  = render 'new_or_edit'