config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'settings' => 'devise/registrations#edit', as: 'edit_settings'
  end

  get 'verify_phone' => 'phone#verify', as: 'verify_phone'
  post 'verify_phone' => 'phone#check_pin', as: 'check_pin'

  get 'about' => 'about#index', as: 'about'

  get 'billing' => 'billing#index', as: 'billing'

  resources :trails do
    member do
      get 'admin'
      post 'create_photo'
    end
  end
  resources :instagram_photos, only: :destroy
  resources :alerts
  resource :subscriptions, as: :subscription
end

app/views/common/_flash_messages.html.haml
- flash.to_hash.each do |key, message|
  .alert.flash.fade.in{class: bootstrap_alert_type(key), data: { alert: 'alert' }}
    .container
      %p
        %a.close{href: '#', 'data-dismiss' => 'alert'} &times;
        = message

app/views/common/_google_analytics.html.haml
- if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-7385360-20', 'auto');
    ga('send', 'pageview');

app/views/common/_navigation.html.haml
.container
  .header.clearfix
    %nav.navbar
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{type: 'button', 'data-toggle' => 'collapse', 'data-target' => '#navbar-collapse', 'aria-expanded' => 'false'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to('MTB Trail Status', :root, class: 'navbar-brand')
        .collapse.navbar-collapse{id: 'navbar-collapse'}
          %ul.nav.navbar-nav.nav-pills.navbar-right
            %li{class: (@nav == 'trails' ? 'active' : '')}
              = link_to 'Trails', trails_path
            %li{role: 'presentation', class: (@nav == 'about' ? 'active' : '')}
              = link_to 'About', about_path
            - if current_user
              %li{class: (@nav == 'alerts' ? 'active' : '')}
                = link_to 'My Alerts', alerts_path
              %li.dropdown
                = link_to('#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false') do
                  = current_user.email
                  %span.caret
                %ul.dropdown-menu
                  %li{role: 'presentation'}
                    = link_to 'Settings', edit_settings_path
                  - unless current_user.is_comped?
                    - if current_user.subscription
                      %li{role: 'presentation'}
                        - link_text = current_user.subscription.canceled? ? 'Add Subscription' : 'Edit Subscription'
                        = link_to link_text, edit_subscription_path
                      %li{role: 'presentation'}
                        = link_to 'Billing', billing_path
                    - else
                      %li{role: 'presentation'}
                        = link_to 'Add Subscription', new_subscription_path
                  %li{role: 'presentation'}
                    = link_to 'Sign Out', destroy_user_session_path, method: :delete
            - else
              %li{role: 'presentation'}
                = link_to 'Sign In', new_user_session_path
              %li{role: 'presentation'}
                = link_to 'Sign Up', new_user_registration_path

app/views/common/_stripe.html.haml
%script{src: 'https://js.stripe.com/v2/'}
%script
  Stripe.setPublishableKey("#{Rails.configuration.stripe[:publishable_key]}");

app/views/common/_trail_status_tabs.html.haml
.btn-group.btn-group-sm.trail-status-tabs{role: 'group tab-list'}
  %a.btn.btn-default.selected{href: '#tab-list', role: 'tab presentation', 'data-toggle' => 'tab'}
    %i.glyphicon.glyphicon-list
    View List
  %a.btn.btn-default{href: '#tab-map', role: 'tab presentation', 'data-toggle' => 'tab'}
    %i.glyphicon.glyphicon-map-marker
    View Map

app/views/common/_trail_statuses.html.haml
%h2
  Current Trail Statuses
  .pull-right.hidden-xs
    = render 'common/trail_status_tabs'

.visible-xs{style: 'text-align: center; margin-bottom: 10px;'}
  = render 'common/trail_status_tabs'

.tab-content
  .tab-pane.active{id: 'tab-list'}
    %table.table.table-striped.statuses
      %tbody
        - @trails.each do |trail|
          - glyphicon = trail.status == 'open' ? 'glyphicon-ok' : 'glyphicon-remove'
          %tr.trail
            %td.name
              %h3
                = link_to trail do
                  %i.glyphicon{class: "#{glyphicon} #{trail.status}"}
                  = trail.display_name
            %td.date
              %span.status{class: "#{trail.status}"}= trail.status
              %span.text-muted{title: "#{trail.status_updated_at}"}
                = time_ago_in_words trail.status_updated_at
                ago
  .tab-pane{id: 'tab-map'}
    #map.map